### PR TITLE
Fixed typo with 'Debian\b'

### PR DESCRIPTION
**Pull request by yk12OT**
added downcase for ::osfamily fact verification

### CODE REVIEW

**Comment by liamjbennett** [comment]
Why is this required? What version of facter is causing you problems?

**Comment by yk12OT** [comment]
yesterday it failed in my Vagrant for Ubuntu12 box fresh installation.

today it seems to work just fine (after I 'git pull' puppet modules and destroyed ubuntu 12 test box. Closing PR since it seems to work OK.

I used a node file like this, but that is probably irrelevant:

node    'ubuntu2.vagrant.local'
{
  include roles::avstore_redis_with_sentinel_eu_test
}

**Comment by SegFaultAX** [comment]
The issue is in facter (tested versions 2.3.0 and 2.4.3), the osfamily fact is reported as exactly "Debian" which the validation fails to match, causing the catalog to entirely fail. @yk12OT's fix replaces the singular RE with a list of REs and also does the check only against the downcased osfamily.

For clarity, the "typo" he's referring to isn't actually a typo, and I've shared some examples with him of word boundaries. In any case, the `\b` is a red herring and the actual issue is case-sensitive matching.

**Comment by SegFaultAX** [comment]
Final note: the test failures on this branch are related to i18n failing to install on 1.8.7 and appear to be unrelated this PR.

**Pull request merged**
